const Programs= [
        {
            "id": 1,
            "program": "Accounting",
            "certification": "Bachelor of Commerce with specialization in Accounting (BComm)",
            "faculty": "School of Business",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://www.freshbooks.com/wp-content/uploads/2022/02/8-branches-of-accounting.jpg"
        },
        {
            "id": 2,
            "program": "Actuarial Science",
            "certification": "Bachelor of Science (BSc)",
            "faculty": "School of Business",
            "title": "Unlocking the World of Risk Management and Financial Analysis",
            "info": "The Actuarial Science program at school is designed to equip students with the skills and knowledge required to become proficient actuaries in the dynamic and ever-evolving world of risk management and financial analysis. Actuaries are essential professionals in various industries, especially insurance, finance, and consulting, as they play a critical role in assessing and managing risk.",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "The Actuarial Science Program provides students with a comprehensive skill set to excel in the actuarial profession, making them valuable assets in risk management and financial planning across various industries",
            "imageURL": "https://sell.g2.com/hubfs/actuarial-science.jpg"
        },
        {
            "id": 3,
            "program": "Anatomy",
            "certification": "Bachelor of Science (BSc)",
            "faculty": "Faculty of Basic Medical Science",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://www.ualberta.ca/medicine/media-library/programs/md-program/website-update/elevatorcover.jpg"
        },
        {
            "id": 4,
            "program": "Anthropology",
            "certification": "Bachelor of Arts (BA)",
            "faculty": "Faculty of Arts",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://www.niu.edu/academics/undergraduate/images/anthropology.jpg"
        },
        {
            "id": 5,
            "program": "Aeronautical Engineering",
            "certification": "Bachelor of Engineering (BEng)",
            "faculty": "Faculty of Engineering",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://daytonabeach.erau.edu/-/media/images/daytona-beach/coe/ae-homepage.jpg?as=0&hash=10EE8B71AC1D5C525FB22BE8F20878C1"
        },
        {
            "id": 6,
            "program": "African and Asian Studies",
            "certification": "Bachelor of Arts (BA)",
            "faculty": "Faculty of Arts",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7pldphYhnapqcp9UlkTAzF1Hh6QwkMtopjg&usqp=CAU"
        },
        {
            "id": 7,
            "program": "Archaeology",
            "certification": "Bachelor of Arts (BA)",
            "faculty": "Faculty of Arts",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://www.archaeological.org/wp-content/uploads/2019/05/10462426_319125484903742_6095597394966512761_o_2.jpg"
        },
        {
            "id": 8,
            "program": "Artificial Intelligence and Machine Learning",
            "certification": "Bachelor of Technology (BTech)",
            "faculty": "Faculty of Computer Science",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://sru.edu.in/assets/schools/cse/ai-ml-banner.png"
        },
        {
            "id": 9,
            "program": "Automobile Engineering",
            "certification": "Bachelor of Engineering (BEng)",
            "faculty": "Faculty of Engineering",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://iukl.edu.my/wp-content/uploads/2018/01/diploma-in-automotive-engineering.png"
        },
        {
            "id": 10,
            "program": "Biomedical Sciences",
            "certification": "Bachelor of Science (BSc)",
            "faculty": "Faculty of Medical Science",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://beal.edu/wp-content/uploads/2019/09/istock_9534994-hero.jpg"
        },
        {
            "id": 11,
            "program": "Biochemistry",
            "certification": "Bachelor of Science (BSc)",
            "faculty": "Faculty of Sciences",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://www.arbor.edu/wp-content/uploads/2019/06/Biochemistry_web.jpg"
        },
        {
            "id": 12,
            "program": "Business Management",
            "certification": "Bachelor of Business Administration (BBA)",
            "faculty": "Faculy of Business Management",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://www.bridgeport.edu/files/images/headers/majors-sps.jpg"
        },
        {
            "id": 13,
            "program": "Business Studies",
            "certification": "Bachelor of Business Administration (BBA)",
            "faculty": "Faculty of Business Management",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://www.bridgeport.edu/files/images/headers/majors-sps.jpg"
        },
        {
            "id": 14,
            "program": "Chemical Engineering",
            "certification": "Bachelor of Science (BSc)",
            "faculty": "Faculty of Engineering",
            "title": "Lorem ipsum dolor sit amet consectetur",
            "info": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla praesentium amet voluptas rem reiciendis harum, minima ipsa molestias accusamus eveniet porro? Similique vero velit nostrum delectus maxime exercitationem officiis. A beatae autem sequi sed! Neque id officiis quam modi nulla, culpa omnis sequi ut deserunt, cumque nesciunt beatae aspernatur earum non? Similique sunt sit asperiores officia enim? Modi, tenetur culpa!",
            "duration": "Four years",
            "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto hic qui vel in quidem saepe consectetur, laboriosam reprehenderit animi voluptatem magni laudantium, repudiandae necessitatibus ut, ipsa atque facilis illo eos harum alias et! Nulla dolorum placeat corporis nisi rerum maxime quia perspiciatis, eius ratione quam consequatur numquam quaerat. Nam quasi error omnis facere quaerat amet voluptate cum corporis veniam maiores sunt, iure ad alias labore, veritatis aspernatur quis dolore rerum aliquid nobis, voluptatem recusandae voluptatum at necessitatibus. Blanditiis, id ad.",
            "curriculum": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non sed sit fuga, pariatur iusto nobis natus dolore eveniet. Quibusdam provident corporis totam molestias laboriosam nemo ducimus commodi quis. Ex quidem, recusandae tenetur officia nihil, eum fugit reiciendis placeat asperiores enim consequuntur vitae. Dolorem, cum aliquam?",
            "imageURL": "https://che.udel.edu/wp-content/uploads/2019/03/Summer_Research-Sharief-3D_Printed_Lung_Model-080218-018.jpg"
        },
        
    ]

    export default Programs;